#!/bin/sh
set -eu
: "${EDUAMIGAE_1X_KICKSTART:?set EDUAMIGAE_1X_KICKSTART}"
: "${EDUAMIGAE_1X_SYSTEM:?set EDUAMIGAE_1X_SYSTEM}"
export EDUAMIGAE_A500_KICKSTART="$EDUAMIGAE_1X_KICKSTART"
export EDUAMIGAE_A500_SYSTEM="$EDUAMIGAE_1X_SYSTEM"
exec sh "$(dirname "$0")/qualify-target.sh" a500-1x "$@"
